### ISSUE TITLE
localhost:8000 page still shows backend page after integrating with frontend 

### ISSUE THREAD

**Issue by TracyTingjia** [Onlynfk/django-react-starter-guide#3]
Hello, I started with setting up backend and it went all fine. I was able to the page I set up in view.py.
after integrating with frontend, it does not reflect with the homepage.js. I do not have any error occuring by running npm run dev.
Thanks in advance.

**Comment by Onlynfk** [comment]
Hi @TracyTingjia  thanks for checking by, but could you check on the build dist folder on your end, there could be an issue on it probably with the index.html,  cause it would build all components in the frontend and also watch for changes, when you run npm run dev,

Let me know if the issue persist. Cheers

**Comment by TracyTingjia** [comment]
<img width="870" alt="Screenshot 2023-04-12 at 7 17 50 PM" src="https://user-images.githubusercontent.com/48410261/231606530-5b8252b5-814a-4137-af9e-9215d3b53909.png">
Thanks for your response. Please check the screenshot, it does not seem to be an issue.
The index.html is exact same as yours under templates/frontend. main.js was also generated. so not sure what is preventing the integration between ReactJs and Django.

**Comment by Onlynfk** [comment]
Ok I see, will check on this again,  when I can and share feedback

**Comment by TracyTingjia** [comment]
I got it. I forgot to include urls.py in setting.py file. Thank you for looking into it.

**Comment by Onlynfk** [comment]
Oh nice, Great!
would plan on writing more content these days
Thanks and Cheers
